---
- name: Copy script to remote machine
  copy:
    src: "{{ item }}"
    dest: /root/
    owner: root
    group: root
    mode: '0555'
  with_items:
    - smallfile_test_for_fuse.sh
    - sync-and-drop-cache.yml
    - ansible.cfg

- name: Copy inventroy file with the name hosts
  copy:
    src: "{{ inventory_file }}"
    dest: /root/hosts
    owner: root
    group: root
    mode: '0555'

- name: Commenting vault pass line
  lineinfile:
    path: /root/ansible.cfg
    regexp: '^vault_password_file[.]*'
    line: '#vault_password_file'
    backrefs: yes

- name: Create config scripts
  template:
    src: templates/client.j2
    dest: /root/client.ioz
    mode: '0644'

- name: Setting up ssh config
  lineinfile:
    path: /etc/ssh/ssh_config
    line: "{{ item }}"
    insertbefore: BOF
  with_items:
    - 'StrictHostKeyChecking=no'
    - 'UserKnownHostsFile="/dev/null"'

- name: delete the logs of any previous runs
  file:
    path: /root/fuse_and_gnfs_mount_result.txt
    state: absent
  with_items:
    - /root/fuse_and_gnfs_mount_result.txt
    - /root/PerfTest.log
    - /root/profile-for-fuse-and-gnfs.tar
    - /root/profile-for-fuse-and-gnfs

- name: Run perf test
  shell: "/root/smallfile_test_for_fuse.sh \"{{node0}}\" /root/fuse_and_gnfs_mount_result.txt > /root/fuse_and_gnfs_mount_result.txt 2>&1"
  async: 21600                                 # waiting for 6 hours for test to complete, if it finishes early poll will detect that and report
  poll: 900
  register: perf_test

- name: fetch a file from remote machine
  fetch:
    src: "{{ item }}"
    dest: ./results/
    flat: yes
  with_items:
    - /root/fuse_and_gnfs_mount_result.txt
    - /root/PerfTest.log
