---
- name: Setup ssh key for root user
  user:
    name: root
    generate_ssh_key: true

- name: Edit yum.conf to not install docs
  lineinfile:
    path: '/etc/yum.conf'
    state: present
    line: 'tstflags=nodocs'
