---
- name: Create directory for small-files
  file:
    path: /small-files/smallfile
    state: directory
    mode: '0755'

- name: Install smallfile
  git:
    repo: 'https://github.com/bengland2/smallfile.git'
    dest: /small-files/smallfile
    depth: 1
    version: e8e7bf5f658664d2a2b0a2f5c8c7beb4b20cd704

- name: Installing Iozone
  yum:
    name: https://www.rpmfind.net/linux/dag/redhat/el7/en/x86_64/dag/RPMS/iozone-3.424-2.el7.rf.x86_64.rpm
    state: present
