---
- name: Install glusterfs-fuse
  yum:
    name: [ 'glusterfs-fuse' ]
    state: present
  retries: 10
  delay: 5

- name: Install additional packages on master client
  yum:
    name: [ 'sshpass', 'ansible', 'git' ]
    state: present
  retries: 10
  delay: 5
  when: inventory_hostname == groups['master_client'].0

- name: distribute the ssh key to the remote hosts
  shell: "/usr/bin/sshpass -p \"{{ remote_machine_password }}\" ssh-copy-id -f -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/{{ ssh_key_filename }}.pub  \"{{ remote_machine_username }}@{{ item }}\""
  register: ssh_copy_id_execution
  with_items:
    - "{{ groups['cluster_machines']}}"
  failed_when: ssh_copy_id_execution.rc != 0
  when: inventory_hostname == groups['master_client'].0
