---
- name: Install Gluster-ansible and additional packages on client
  yum:
    name: [ 'sshpass', 'glusterfs-fuse' , 'ansible', 'git' ]
    state: present
  retries: 10
  delay: 5

- name: distribute the ssh key to the remote hosts
  shell: "/usr/bin/sshpass -p \"{{remote_machine_password}}\" ssh-copy-id -f -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/{{ssh_key_filename}}.pub  \"{{remote_machine_username}}@{{ item }}\""
  register: ssh_copy_id_execution
  with_items:
    - "{{ groups['cluster_machines']}}"
  failed_when: ssh_copy_id_execution.rc != 0
