---
- name: Install Gluster and additional packages on servers
  yum:
    name: ['python3',  'glusterfs-server', 'glusterfs-fuse', 'glusterfs-api' ]
    state: present
  retries: 10
  delay: 5

- name: Restart services
  systemd:
    name: "{{ item }}"
    daemon_reload: yes
    state: restarted
  with_items:
   - 'glusterd'
