---
- name: Add EPEL repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    mirrorlist: https://mirrors.fedoraproject.org/mirrorlist?repo=epel-7&arch=$basearch
    enabled: yes
    gpgcheck: no
    keepalive: yes

- name: Configure Gluster master nightly repo
  yum_repository:
    name: "gluster-nightly-master"
    description: "Gluster Nightly builds (master branch)"
    baseurl: "http://artifacts.ci.centos.org/gluster/nightly/master/7/x86_64"
    gpgcheck: false
    repo_gpgcheck: false
    keepalive: yes
